spring.application.name=salones
server.port=8081
spring.datasource.url=jdbc:mysql://${HOST:172.30.219.232}:${PORT:3306}/ocasion_salon_db?serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:dom2dbOcasion}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#JWT
jwt.secret={JWT_SECRET}